# Name of this app
service: fizzy
image: fizzy


#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    hosts: <%= ENV.fetch("WEB_HOSTS").split(",").map(&:strip) %>

# How you connect to your server
ssh:
  user: debian  # If you use a different username to SSH to your server, specify it here

# Automatic SSL
proxy:
  ssl: true                # Set this to false if you *don"t* want SSL
  host: <%= ENV.fetch("PROXY_HOST") %>  # Set your server name here to use automatic SSL

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
  clear:
    BASE_URL: <%= ENV.fetch("BASE_URL") %> # The public URL of your Fizzy instance
    SMTP_ADDRESS: <%= ENV.fetch("SMTP_ADDRESS") %>
    SMTP_DOMAIN: <%= ENV.fetch("SMTP_DOMAIN") %>
    SMTP_AUTHENTICATION: <%= ENV.fetch("SMTP_AUTHENTICATION") %>
    MAILER_FROM_ADDRESS: <%= ENV.fetch("MAILER_FROM_ADDRESS") %>  # The email "from" address that Fizzy sends email from
    MULTI_TENANT: false # Set to true to allow multiple accounts to sign up
    SOLID_QUEUE_IN_PUMA: true # Run background jobs in the app container
    ACTIVE_STORAGE_SERVICE: s3
    S3_REGION: <%= ENV.fetch("S3_REGION") %>
    S3_BUCKET: <%= ENV.fetch("S3_BUCKET") %>
    CSP_CONNECT_SRC: https://<%= ENV.fetch("S3_BUCKET") %>.s3.<%= ENV.fetch("S3_REGION") %>.amazonaws.com
    CSP_IMG_SRC: https://<%= ENV.fetch("S3_BUCKET") %>.s3.<%= ENV.fetch("S3_REGION") %>.amazonaws.com


#-- General configuration --#

# Use a local registry to deploy
registry:
  server: localhost:5555

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
